// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABl0EWrwlwxO7zUpyl9jYgkbJoXNiijOk',
    appId: '1:567547480243:web:24f553903df22c96f8c8c6',
    messagingSenderId: '567547480243',
    projectId: 'fir-3aa3a',
    authDomain: 'fir-3aa3a.firebaseapp.com',
    storageBucket: 'fir-3aa3a.firebasestorage.app',
    measurementId: 'G-47831WSLG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT0dUpIi4gJSyzLNOm6puzaF4Z1IXG9cE',
    appId: '1:567547480243:android:c76740f7598d1f50f8c8c6',
    messagingSenderId: '567547480243',
    projectId: 'fir-3aa3a',
    storageBucket: 'fir-3aa3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfinXwStTRRkg58mrw0NzF2Unmlp1Mu7M',
    appId: '1:567547480243:ios:a6c79627450d75fef8c8c6',
    messagingSenderId: '567547480243',
    projectId: 'fir-3aa3a',
    storageBucket: 'fir-3aa3a.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrudNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfinXwStTRRkg58mrw0NzF2Unmlp1Mu7M',
    appId: '1:567547480243:ios:a6c79627450d75fef8c8c6',
    messagingSenderId: '567547480243',
    projectId: 'fir-3aa3a',
    storageBucket: 'fir-3aa3a.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrudNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABl0EWrwlwxO7zUpyl9jYgkbJoXNiijOk',
    appId: '1:567547480243:web:462bc8d8c7d414d8f8c8c6',
    messagingSenderId: '567547480243',
    projectId: 'fir-3aa3a',
    authDomain: 'fir-3aa3a.firebaseapp.com',
    storageBucket: 'fir-3aa3a.firebasestorage.app',
    measurementId: 'G-ZT24TYWRQT',
  );
}
